version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: mudik-pgn-app
    container_name: mudik-pgn-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8004:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    env_file:
      - .env.docker

  db:
    image: mysql:8.0
    container_name: mudik-pgn-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env.docker

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: